// Generated by scripts/import-toyota-interiors.py from the supplied Toyota index.
export type InteriorView = "side" | "driver" | "passenger" | "bird";
export type ToyotaInterior = { id: string; code: string; name: { he: string; en: string }; hex: string; views: { id: InteriorView; src: string }[] };
export const TOYOTA_INTERIORS: Record<string, Record<string, ToyotaInterior[]>> = {
  "4runner": {
    "limited": [
      {
        "id": "20la",
        "code": "20LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/limited/20la/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/limited/20la/bird.webp"
          }
        ]
      },
      {
        "id": "45la",
        "code": "45LA",
        "name": {
          "en": "Portobello Leather",
          "he": "עור פורטובלו"
        },
        "hex": "#796252",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/limited/45la/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/limited/45la/bird.webp"
          }
        ]
      }
    ],
    "sr5": [
      {
        "id": "20fa",
        "code": "20FA",
        "name": {
          "en": "Black Fabric",
          "he": "בד שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/sr5/20fa/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/sr5/20fa/bird.webp"
          }
        ]
      }
    ],
    "trd-off-road": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/trd-off-road/20ea/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/trd-off-road/20ea/bird.webp"
          }
        ]
      }
    ],
    "trd-sport": [
      {
        "id": "11fb",
        "code": "11FB",
        "name": {
          "en": "Grey/Black Fabric · 11FB",
          "he": "בד אפור / שחור · 11FB"
        },
        "hex": "linear-gradient(135deg, #aaa9a4 50%, #202020 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/trd-sport/11fb/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/trd-sport/11fb/bird.webp"
          }
        ]
      },
      {
        "id": "12fb",
        "code": "12FB",
        "name": {
          "en": "Grey/Black Fabric · 12FB",
          "he": "בד אפור / שחור · 12FB"
        },
        "hex": "linear-gradient(135deg, #aaa9a4 50%, #202020 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/4runner/trd-sport/12fb/side.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/4runner/trd-sport/12fb/bird.webp"
          }
        ]
      }
    ]
  },
  "camry": {
    "nightshade": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black Mixed Fabric & SofTex",
          "he": "בד וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/nightshade/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/nightshade/20ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/nightshade/20ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/nightshade/20ea/bird.webp"
          }
        ]
      }
    ],
    "se": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black Mixed Fabric & SofTex",
          "he": "בד וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/se/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/se/20ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/se/20ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/se/20ea/bird.webp"
          }
        ]
      }
    ],
    "se-upgrade": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black Mixed Fabric & SofTex",
          "he": "בד וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/se-upgrade/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/se-upgrade/20ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/se-upgrade/20ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/se-upgrade/20ea/bird.webp"
          }
        ]
      }
    ],
    "se-upgrade-awd": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black Mixed Fabric & SofTex",
          "he": "בד וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/se-upgrade-awd/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/se-upgrade-awd/20ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/se-upgrade-awd/20ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/se-upgrade-awd/20ea/bird.webp"
          }
        ]
      }
    ],
    "xle": [
      {
        "id": "10la",
        "code": "10LA",
        "name": {
          "en": "Grey Quilting Leather",
          "he": "עור בתפירת קווילט אפור"
        },
        "hex": "#999a96",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/xle/10la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/xle/10la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/xle/10la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/xle/10la/bird.webp"
          }
        ]
      },
      {
        "id": "20la",
        "code": "20LA",
        "name": {
          "en": "Black Quilting Leather",
          "he": "עור בתפירת קווילט שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/xle/20la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/xle/20la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/xle/20la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/xle/20la/bird.webp"
          }
        ]
      }
    ],
    "xse": [
      {
        "id": "20lb",
        "code": "20LB",
        "name": {
          "en": "Black Sports Leather",
          "he": "עור ספורטיבי שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/xse/20lb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/xse/20lb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/xse/20lb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/xse/20lb/bird.webp"
          }
        ]
      },
      {
        "id": "30lb",
        "code": "30LB",
        "name": {
          "en": "Red Sports Leather",
          "he": "עור ספורטיבי אדום"
        },
        "hex": "#86252b",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/camry/xse/30lb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/camry/xse/30lb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/camry/xse/30lb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/camry/xse/30lb/bird.webp"
          }
        ]
      }
    ]
  },
  "crown": {
    "limited": [
      {
        "id": "20la",
        "code": "20LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/crown/limited/20la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/crown/limited/20la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/crown/limited/20la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/crown/limited/20la/bird.webp"
          }
        ]
      }
    ],
    "platinum": [
      {
        "id": "20la",
        "code": "20LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/crown/platinum/20la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/crown/platinum/20la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/crown/platinum/20la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/crown/platinum/20la/bird.webp"
          }
        ]
      }
    ]
  },
  "grand-highlander": {
    "hybrid-limited-7": [
      {
        "id": "20lc",
        "code": "20LC",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-7/20lc/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-7/20lc/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-7/20lc/bird.webp"
          }
        ]
      }
    ],
    "hybrid-limited-8": [
      {
        "id": "20lc",
        "code": "20LC",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-8/20lc/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-8/20lc/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/hybrid-limited-8/20lc/bird.webp"
          }
        ]
      }
    ],
    "hybrid-xle": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/hybrid-xle/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/hybrid-xle/20ea/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/hybrid-xle/20ea/bird.webp"
          }
        ]
      }
    ],
    "limited": [
      {
        "id": "20lc",
        "code": "20LC",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/limited/20lc/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/limited/20lc/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/limited/20lc/bird.webp"
          }
        ]
      }
    ],
    "platinum": [
      {
        "id": "20la",
        "code": "20LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/platinum/20la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/platinum/20la/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/platinum/20la/bird.webp"
          }
        ]
      },
      {
        "id": "40la",
        "code": "40LA",
        "name": {
          "en": "Portobello Leather",
          "he": "עור פורטובלו"
        },
        "hex": "#796252",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/platinum/40la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/platinum/40la/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/platinum/40la/bird.webp"
          }
        ]
      }
    ],
    "xle": [
      {
        "id": "20ea",
        "code": "20EA",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/grand-highlander/xle/20ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/grand-highlander/xle/20ea/driver.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/grand-highlander/xle/20ea/bird.webp"
          }
        ]
      }
    ]
  },
  "land-cruiser": {
    "1958": [
      {
        "id": "20fb",
        "code": "20FB",
        "name": {
          "en": "Black Cloth",
          "he": "בד שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/land-cruiser/1958/20fb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/land-cruiser/1958/20fb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/land-cruiser/1958/20fb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/land-cruiser/1958/20fb/bird.webp"
          }
        ]
      }
    ],
    "land-cruiser": [
      {
        "id": "20eb",
        "code": "20EB",
        "name": {
          "en": "Black Softex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/land-cruiser/land-cruiser/20eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/land-cruiser/land-cruiser/20eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/land-cruiser/land-cruiser/20eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/land-cruiser/land-cruiser/20eb/bird.webp"
          }
        ]
      }
    ],
    "premium": [
      {
        "id": "20lb",
        "code": "20LB",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/land-cruiser/premium/20lb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/land-cruiser/premium/20lb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/land-cruiser/premium/20lb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/land-cruiser/premium/20lb/bird.webp"
          }
        ]
      },
      {
        "id": "40lb",
        "code": "40LB",
        "name": {
          "en": "Java Leather",
          "he": "עור ג׳אווה"
        },
        "hex": "#674332",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/land-cruiser/premium/40lb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/land-cruiser/premium/40lb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/land-cruiser/premium/40lb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/land-cruiser/premium/40lb/bird.webp"
          }
        ]
      }
    ]
  },
  "prius-phev": {
    "se": [
      {
        "id": "23fa",
        "code": "23FA",
        "name": {
          "en": "Black Cloth",
          "he": "בד שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/prius-phev/se/23fa/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/prius-phev/se/23fa/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/prius-phev/se/23fa/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/prius-phev/se/23fa/bird.webp"
          }
        ]
      }
    ],
    "xse": [
      {
        "id": "22ea",
        "code": "22EA",
        "name": {
          "en": "Black / Red SofTex/Fabric",
          "he": "סופטקס ובד שחור / אדום"
        },
        "hex": "linear-gradient(135deg, #202020 50%, #86252b 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/prius-phev/xse/22ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/prius-phev/xse/22ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/prius-phev/xse/22ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/prius-phev/xse/22ea/bird.webp"
          }
        ]
      }
    ],
    "xse-premium": [
      {
        "id": "22ea",
        "code": "22EA",
        "name": {
          "en": "Black / Red SofTex/Fabric",
          "he": "סופטקס ובד שחור / אדום"
        },
        "hex": "linear-gradient(135deg, #202020 50%, #86252b 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/prius-phev/xse-premium/22ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/prius-phev/xse-premium/22ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/prius-phev/xse-premium/22ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/prius-phev/xse-premium/22ea/bird.webp"
          }
        ]
      }
    ]
  },
  "rav4-prime": {
    "gr-sport": [
      {
        "id": "20ed",
        "code": "20ED",
        "name": {
          "en": "Black Mixed Synthetic Suede & Softex",
          "he": "זמש סינתטי וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/rav4-prime/gr-sport/20ed/side.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/rav4-prime/gr-sport/20ed/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/rav4-prime/gr-sport/20ed/bird.webp"
          }
        ]
      }
    ],
    "se": [
      {
        "id": "20fc",
        "code": "20FC",
        "name": {
          "en": "Black Cloth",
          "he": "בד שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/rav4-prime/se/20fc/side.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/rav4-prime/se/20fc/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/rav4-prime/se/20fc/bird.webp"
          }
        ]
      }
    ],
    "xse": [
      {
        "id": "20ec",
        "code": "20EC",
        "name": {
          "en": "Black Mixed Synthetic Suede & Softex",
          "he": "זמש סינתטי וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/rav4-prime/xse/20ec/side.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/rav4-prime/xse/20ec/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/rav4-prime/xse/20ec/bird.webp"
          }
        ]
      }
    ],
    "xse-tech": [
      {
        "id": "20ec",
        "code": "20EC",
        "name": {
          "en": "Black Mixed Synthetic Suede & Softex",
          "he": "זמש סינתטי וסופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/rav4-prime/xse-tech/20ec/side.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/rav4-prime/xse-tech/20ec/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/rav4-prime/xse-tech/20ec/bird.webp"
          }
        ]
      }
    ]
  },
  "sequoia": {
    "capstone": [
      {
        "id": "15lc",
        "code": "15LC",
        "name": {
          "en": "Shale Semi-Aniline Leather",
          "he": "עור חצי־אנילין שייל"
        },
        "hex": "#c8c3b7",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/capstone/15lc/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/capstone/15lc/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/capstone/15lc/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/capstone/15lc/bird.webp"
          }
        ]
      }
    ],
    "capstone-tow": [
      {
        "id": "15lc",
        "code": "15LC",
        "name": {
          "en": "Shale Semi-Aniline Leather",
          "he": "עור חצי־אנילין שייל"
        },
        "hex": "#c8c3b7",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/capstone-tow/15lc/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/capstone-tow/15lc/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/capstone-tow/15lc/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/capstone-tow/15lc/bird.webp"
          }
        ]
      }
    ],
    "nightshade": [
      {
        "id": "13ld",
        "code": "13LD",
        "name": {
          "en": "Grey Leather",
          "he": "עור אפור"
        },
        "hex": "#999a96",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/nightshade/13ld/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/nightshade/13ld/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/nightshade/13ld/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/nightshade/13ld/bird.webp"
          }
        ]
      },
      {
        "id": "21ld",
        "code": "21LD",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/nightshade/21ld/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/nightshade/21ld/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/nightshade/21ld/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/nightshade/21ld/bird.webp"
          }
        ]
      }
    ],
    "platinum": [
      {
        "id": "21la",
        "code": "21LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/platinum/21la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/platinum/21la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/platinum/21la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/platinum/21la/bird.webp"
          }
        ]
      }
    ],
    "platinum-tow": [
      {
        "id": "21la",
        "code": "21LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/platinum-tow/21la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/platinum-tow/21la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/platinum-tow/21la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/platinum-tow/21la/bird.webp"
          }
        ]
      }
    ],
    "sr5-trd-off-road": [
      {
        "id": "21le",
        "code": "21LE",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/sr5-trd-off-road/21le/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/sr5-trd-off-road/21le/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/sr5-trd-off-road/21le/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/sr5-trd-off-road/21le/bird.webp"
          }
        ]
      }
    ],
    "trd-pro": [
      {
        "id": "21eb",
        "code": "21EB",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/trd-pro/21eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/trd-pro/21eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/trd-pro/21eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/trd-pro/21eb/bird.webp"
          }
        ]
      },
      {
        "id": "33eb",
        "code": "33EB",
        "name": {
          "en": "Cockpit Red SofTex",
          "he": "סופטקס אדום קוקפיט"
        },
        "hex": "#86252b",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sequoia/trd-pro/33eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sequoia/trd-pro/33eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sequoia/trd-pro/33eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sequoia/trd-pro/33eb/bird.webp"
          }
        ]
      }
    ]
  },
  "sienna": {
    "le-awd": [
      {
        "id": "15fa",
        "code": "15FA",
        "name": {
          "en": "Gray Fabric",
          "he": "בד אפור"
        },
        "hex": "#999a96",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/le-awd/15fa/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/le-awd/15fa/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/le-awd/15fa/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/le-awd/15fa/bird.webp"
          }
        ]
      }
    ],
    "le-awd-mobility": [],
    "le-fwd": [
      {
        "id": "15fa",
        "code": "15FA",
        "name": {
          "en": "Gray Fabric",
          "he": "בד אפור"
        },
        "hex": "#999a96",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/le-fwd/15fa/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/le-fwd/15fa/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/le-fwd/15fa/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/le-fwd/15fa/bird.webp"
          }
        ]
      }
    ],
    "le-fwd-mobility": [],
    "limited": [
      {
        "id": "25la",
        "code": "25LA",
        "name": {
          "en": "Black Leather",
          "he": "עור שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/limited/25la/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/limited/25la/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/limited/25la/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/limited/25la/bird.webp"
          }
        ]
      }
    ],
    "platinum": [
      {
        "id": "42lb",
        "code": "42LB",
        "name": {
          "en": "Macadamia Leather",
          "he": "עור מקדמיה"
        },
        "hex": "#c4ad8c",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/platinum/42lb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/platinum/42lb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/platinum/42lb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/platinum/42lb/bird.webp"
          }
        ]
      }
    ],
    "xle": [
      {
        "id": "15ea",
        "code": "15EA",
        "name": {
          "en": "Gray SofTex",
          "he": "סופטקס אפור"
        },
        "hex": "#999a96",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xle/15ea/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xle/15ea/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xle/15ea/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xle/15ea/bird.webp"
          }
        ]
      }
    ],
    "xle-mobility": [],
    "xse-awd": [
      {
        "id": "16eb",
        "code": "16EB",
        "name": {
          "en": "Gray/ Black SofTex",
          "he": "סופטקס אפור / שחור"
        },
        "hex": "linear-gradient(135deg, #aaa9a4 50%, #202020 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-awd/16eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-awd/16eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-awd/16eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-awd/16eb/bird.webp"
          }
        ]
      },
      {
        "id": "21eb",
        "code": "21EB",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-awd/21eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-awd/21eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-awd/21eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-awd/21eb/bird.webp"
          }
        ]
      }
    ],
    "xse-fwd": [
      {
        "id": "16eb",
        "code": "16EB",
        "name": {
          "en": "Gray/ Black SofTex",
          "he": "סופטקס אפור / שחור"
        },
        "hex": "linear-gradient(135deg, #aaa9a4 50%, #202020 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-fwd/16eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-fwd/16eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-fwd/16eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-fwd/16eb/bird.webp"
          }
        ]
      },
      {
        "id": "21eb",
        "code": "21EB",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-fwd/21eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-fwd/21eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-fwd/21eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-fwd/21eb/bird.webp"
          }
        ]
      }
    ],
    "xse-mobility": [],
    "xse-tech": [
      {
        "id": "16eb",
        "code": "16EB",
        "name": {
          "en": "Gray/ Black SofTex",
          "he": "סופטקס אפור / שחור"
        },
        "hex": "linear-gradient(135deg, #aaa9a4 50%, #202020 50%)",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-tech/16eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-tech/16eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-tech/16eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-tech/16eb/bird.webp"
          }
        ]
      },
      {
        "id": "21eb",
        "code": "21EB",
        "name": {
          "en": "Black SofTex",
          "he": "סופטקס שחור"
        },
        "hex": "#202020",
        "views": [
          {
            "id": "side",
            "src": "interiors/toyota/sienna/xse-tech/21eb/side.webp"
          },
          {
            "id": "driver",
            "src": "interiors/toyota/sienna/xse-tech/21eb/driver.webp"
          },
          {
            "id": "passenger",
            "src": "interiors/toyota/sienna/xse-tech/21eb/passenger.webp"
          },
          {
            "id": "bird",
            "src": "interiors/toyota/sienna/xse-tech/21eb/bird.webp"
          }
        ]
      }
    ]
  }
};
