/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as HondaRouteImport } from './routes/honda'
import { Route as LeasingRouteImport } from './routes/leasing'
import { Route as ToyotaRouteImport } from './routes/toyota'
import { Route as HondaIndexRouteImport } from './routes/honda.index'
import { Route as HondaSlugRouteImport } from './routes/honda.$slug'
import { Route as ToyotaIndexRouteImport } from './routes/toyota.index'
import { Route as ToyotaSlugRouteImport } from './routes/toyota.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const HondaRoute = HondaRouteImport.update({
  id: '/honda',
  path: '/honda',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasingRoute = LeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ToyotaRoute = ToyotaRouteImport.update({
  id: '/toyota',
  path: '/toyota',
  getParentRoute: () => rootRouteImport,
} as any)
const HondaIndexRoute = HondaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HondaRoute,
} as any)
const HondaSlugRoute = HondaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HondaRoute,
} as any)
const ToyotaIndexRoute = ToyotaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToyotaRoute,
} as any)
const ToyotaSlugRoute = ToyotaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToyotaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/honda': typeof HondaRouteWithChildren
  '/leasing': typeof LeasingRoute
  '/toyota': typeof ToyotaRouteWithChildren
  '/honda/$slug': typeof HondaSlugRoute
  '/toyota/$slug': typeof ToyotaSlugRoute
  '/honda/': typeof HondaIndexRoute
  '/toyota/': typeof ToyotaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/leasing': typeof LeasingRoute
  '/honda/$slug': typeof HondaSlugRoute
  '/toyota/$slug': typeof ToyotaSlugRoute
  '/honda': typeof HondaIndexRoute
  '/toyota': typeof ToyotaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/honda': typeof HondaRouteWithChildren
  '/leasing': typeof LeasingRoute
  '/toyota': typeof ToyotaRouteWithChildren
  '/honda/$slug': typeof HondaSlugRoute
  '/toyota/$slug': typeof ToyotaSlugRoute
  '/honda/': typeof HondaIndexRoute
  '/toyota/': typeof ToyotaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/honda'
    | '/leasing'
    | '/toyota'
    | '/honda/$slug'
    | '/toyota/$slug'
    | '/honda/'
    | '/toyota/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/leasing'
    | '/honda/$slug'
    | '/toyota/$slug'
    | '/honda'
    | '/toyota'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/honda'
    | '/leasing'
    | '/toyota'
    | '/honda/$slug'
    | '/toyota/$slug'
    | '/honda/'
    | '/toyota/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  HondaRoute: typeof HondaRouteWithChildren
  LeasingRoute: typeof LeasingRoute
  ToyotaRoute: typeof ToyotaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honda': {
      id: '/honda'
      path: '/honda'
      fullPath: '/honda'
      preLoaderRoute: typeof HondaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leasing': {
      id: '/leasing'
      path: '/leasing'
      fullPath: '/leasing'
      preLoaderRoute: typeof LeasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toyota': {
      id: '/toyota'
      path: '/toyota'
      fullPath: '/toyota'
      preLoaderRoute: typeof ToyotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honda/': {
      id: '/honda/'
      path: '/'
      fullPath: '/honda/'
      preLoaderRoute: typeof HondaIndexRouteImport
      parentRoute: typeof HondaRoute
    }
    '/honda/$slug': {
      id: '/honda/$slug'
      path: '/$slug'
      fullPath: '/honda/$slug'
      preLoaderRoute: typeof HondaSlugRouteImport
      parentRoute: typeof HondaRoute
    }
    '/toyota/': {
      id: '/toyota/'
      path: '/'
      fullPath: '/toyota/'
      preLoaderRoute: typeof ToyotaIndexRouteImport
      parentRoute: typeof ToyotaRoute
    }
    '/toyota/$slug': {
      id: '/toyota/$slug'
      path: '/$slug'
      fullPath: '/toyota/$slug'
      preLoaderRoute: typeof ToyotaSlugRouteImport
      parentRoute: typeof ToyotaRoute
    }
  }
}

interface HondaRouteChildren {
  HondaSlugRoute: typeof HondaSlugRoute
  HondaIndexRoute: typeof HondaIndexRoute
}

const HondaRouteChildren: HondaRouteChildren = {
  HondaSlugRoute: HondaSlugRoute,
  HondaIndexRoute: HondaIndexRoute,
}

const HondaRouteWithChildren = HondaRoute._addFileChildren(HondaRouteChildren)

interface ToyotaRouteChildren {
  ToyotaSlugRoute: typeof ToyotaSlugRoute
  ToyotaIndexRoute: typeof ToyotaIndexRoute
}

const ToyotaRouteChildren: ToyotaRouteChildren = {
  ToyotaSlugRoute: ToyotaSlugRoute,
  ToyotaIndexRoute: ToyotaIndexRoute,
}

const ToyotaRouteWithChildren =
  ToyotaRoute._addFileChildren(ToyotaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  HondaRoute: HondaRouteWithChildren,
  LeasingRoute: LeasingRoute,
  ToyotaRoute: ToyotaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
